import type { Metadata } from "next";
import "./globals.css";
import { Nunito } from 'next/font/google'
import { ToastContainer } from "../components/ToastContainer";
import { AuthGuard } from "../components/AuthGaurd";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const nunito = Nunito({
  weight: '400',
  subsets: ['latin'],
  display: 'swap'
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`h-screen w-screen ${nunito.className} bg-zinc-950 text-zinc-100`}>
        <AuthGuard>
          {children}
        </AuthGuard>
        <ToastContainer />
      </body>
    </html>
  );
}
